### ISSUE TITLE
Bad Request - { "message": "Cannot send an empty message", "code": 50006 }

### ISSUE THREAD

**Issue by heyitsmarlon** [discord-php/DiscordPHP-Http#12]
My application was built using DiscordPHP-Http last year and it worked perfectly up until just recently. No changes have been made to the code but since a few days I get the error `Bad Request - { "message": "Cannot send an empty message", "code": 50006 }`.

What could possibly be the issue?

**Comment by SQKo** [comment]
Please show your code

**Comment by SQKo** [comment]
Duplicate of https://github.com/discord-php/DiscordPHP/issues/797
