### ISSUE TITLE
ReactPHP driver is extremely slow

### ISSUE THREAD

**Issue by Exanlv** [discord-php/DiscordPHP-Http#17]
ReactPHP is extremely slow for some basic requests,

**Guzzle driver test result:**
```
$ ~/Documents/DiscordPHP-Http: ./vendor/bin/phpunit tests/Discord/Drivers/GuzzleTest.php 
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.10
Configuration: (...)/DiscordPHP-Http/phpunit.xml

..........                                                        10 / 10 (100%)

Time: 00:04.446, Memory: 8.00 MB

OK (10 tests, 24 assertions)
```

**React driver test result:**
```
$ ~/Documents/DiscordPHP-Http: ./vendor/bin/phpunit tests/Discord/Drivers/ReactTest.php 
PHPUnit 9.6.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.10
Configuration: (...)/DiscordPHP-Http/phpunit.xml

..........                                                        10 / 10 (100%)

Time: 00:54.402, Memory: 8.00 MB

OK (10 tests, 24 assertions)
```

_Note the difference in execution time_

The tests are based on `Discord\Http\DriverInterface`, the test suites are the exact same.

_I'm still working on the PR which includes these tests, will update the issue with a link to said PR when ready_

Link to test: https://github.com/discord-php/DiscordPHP-Http/commit/a5a8890606fa72dd975217d269e13c82211135bc

**Comment by Exanlv** [comment]
After a trying again just now, unable to recreate the issue. It *might* be something to do with the WiFi at work, but as I haven't had any issues with it before I think this may be a fluke.

Ill try again next week when I go to the office again.

**Comment by Exanlv** [comment]
Tested again at the office today, it is consistently slower here. Not sure why.

After looking into it some more, it *appears* to be an issue with `react/http` and not this library. I'll look into it a bit more in the future to confirm, so I'm leaving the issue open for now.

**Comment by ellisonpatterson** [comment]
It is most likely that by default, ReactPHP HTTP library uses whatever your default DNS server is. DiscordPHP let's you specify the DNS servers that it will use by default. It may resolve your issue.
```
<?php

$dnsConfig = new \React\Dns\Config\Config();
$dnsConfig->nameservers = [
    '1.1.1.1',
    '1.0.0.1',
    '8.8.8.8',
    '8.8.4.4',
];

$discord = new \Discord\Discord([
    'dnsConfig' => $dnsConfig
]);
```

**Comment by Exanlv** [comment]
It's indeed a weird DNS issue, fix would have to be made in ReactPHP-http rather than here. Closing.
